using ModelingToolkit, DifferentialEquations
@variables t
∂ = Differential(t)
include("utils.jl")
include("components/Resistor.jl")
include("components/ConstantVoltage.jl")
include("components/Capacitor.jl")
include("components/Inductor.jl")
include("components/Ground.jl")
include("components/ConstantCurrent.jl")
include("components/VCC.jl")
include("components/VCV.jl")
include("components/CCC.jl")
include("components/CCV.jl")
include("components/IdealOpAmp.jl")
include("components/Switch.jl")